### ISSUE TITLE
Horizontal scroll bar appears when second display is connected

### ISSUE THREAD

**Issue by jaumebosch** [lennymlopes/whynano#16]
See attached screenshot.

<img width="727" alt="Screenshot 2021-05-11 at 12 20 48" src="https://user-images.githubusercontent.com/5648387/117800776-cb6ed480-b253-11eb-94b0-828859adf083.png">

**Comment by jaumebosch** [comment]
BTW MacOS 11.3.1
Chrome Version 90.0.4430.212

**Comment by lennymlopes** [comment]
Can't replicate this behaviour (macOS 11.3.1, Chrome Version 90.0.4430.93).
I'll update and check again.
Did your initial fix solve the issue?

**Comment by jaumebosch** [comment]
Yes, but as I noticed that only happens when dual display and, seems, only in my mac, I won't recommend to merge.
Will do some research to try to find the problem.

Cheers

**Comment by lennymlopes** [comment]
Awesome, thank you!

**Comment by NashJames** [comment]
FYI, same here.

Windows 10. Firefox 88.0.1

Laptop, no additional screens in use.

**Comment by lennymlopes** [comment]
Still can't replicate the issue, but i've tried changing from vw units to %.
I've deployed the changes [here](https://whynano-cc-scroll-bar-ifthf0h4.herokuapp.com), if any of you could check it out that would be great!

**Comment by NashJames** [comment]
Works perfectly for me

**Comment by lennymlopes** [comment]
awesome @NashJames!
i'll wait for @jaumebosch's feedback before i merge to main!

**Comment by lennymlopes** [comment]
i've received a feedback from @jaumebosch on twitter, seems to work for him as well!
merging!
