### ISSUE TITLE
Https redirect

### ISSUE THREAD

**Issue by NashJames** [lennymlopes/whynano#20]
Add a simple redirect to https.

Some browsers like Firefox do this automatically, but most others don't unfortunately.

Someone linked the site recently on a high profile tweet using http, and so anyone following the link will likely have it show up as  'Not Secure'. Which for obvious reasons, is not an ideal look when trying to convince people to join a crypto.

**Comment by lennymlopes** [comment]
You are definitely right. I do not have access to a computer right now, but i'll look into it this monday. Thank you for your input!

**Comment by lennymlopes** [comment]
So i've updated the settings (i'm using heroku for hosting and namecheap for the domain).

The following should work:
- whynano.cc
- www.whynano.cc
- http://whynano.cc
- https://www.whynano.cc

This doesn't redirect to https
- http://www.whynano.cc

This doesn't work at all:
- https://whynano.cc

I've been in contact with namecheap support and their response was as follows:


> Regarding the issue, the redirect for bare domain is created with URL Redirect record. The thing is that https redirect requires SSL certificate to be installed on the server. However, URL Redirect on our Basic nameservers works through our URL Forwarding server. There is no SSL certificate on this server and it is not possible to set a custom one on it, unfortunately. Therefore, it will not be possible to create https redirect.
> We may suggest you to contact your Hosting provider to check if there is any other alternative way to connect the domain to your Hosting account without using URL Redirect in this case.

If anyone has an idea how to fix these issues, i'd be really thankful! In the meantime, i'll try if i can come up with a solution myself.

**Comment by NashJames** [comment]
Much better for some of them!

The 3rd in your list, http://whynano.cc, gets hit by both the HTTPS Everywhere add-on and firefox's natural prevention of http sites. If you go past the blaring warnings and 'accept the risk', it'll then re-direct to https. So not completely ideal, but close!

Also, http://www.whynano.cc did succesfully redirect for me. And I had no warnings from firefox or HTTPS Everywhere. However, it did not redirect when opening the link on iOS safari. So a weird one.

I can't help with the hosting stuff. But you could try some simple JS, it might solve a couple use-cases. Try [here](https://stackoverflow.com/questions/4723213/detect-http-or-https-then-force-https-in-javascript)

**Comment by lennymlopes** [comment]
Thank you for the help! 
I've added the suggested solution and it seems to work great!
I still don't know how to solve the issue with https://whynano.cc not resolving.
I'm not sure about how many people actually use this link anyway though.

**Comment by NashJames** [comment]
Great!

Unfortunately, I just realised for me whynano.cc has the same issue for me as http://whynano.cc. With the warnings. In theory, it should only be noticeable for a small group of people; the more security conscious of us.

I can only suggest contacting your hosting provider. Otherwise, thanks for doing this!

**Comment by lennymlopes** [comment]
I just realized that the changes break whynano.cc, since it redirects it to https://whynano.cc, which does not work.
I'e rolled back the changes and take a closer look tomorrow.

**Comment by lennymlopes** [comment]
I had a little bit of time, so i tried to fix it. 
Looks alright to me, but if you @NashJames could have a quick look, that would be great!

**Comment by NashJames** [comment]
All of them work perfectly! Nice job

**Comment by lennymlopes** [comment]
Awesome! Thank you!
